apiVersion: 1

datasources:
  - name: InfluxDB
    version: 2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    uid: P951FEA4DE68E13C5
    jsonData:
      defaultBucket: vechain
      httpMode: POST
      organization: vechain
      version: Flux
      timeInterval: 10s
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
